package aopExamProject.dices;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JCheckBox;
import javax.swing.JPanel;

public class DiceImage extends JPanel {
	private static final int SIZE = 100;
	private int value;
	private JCheckBox lockBox;
	
	public DiceImage(int v, JCheckBox box) {
		value = v;
		lockBox = box;
		
		// Generated by Claude:
		setLayout(null); // disable layout management — positions are manual now
        add(lockBox);
        lockBox.setBounds(SIZE -20, SIZE - 20, 20, 20); // x, y, width, height
	}
	
	public void setValue(int v) {
		value = v;
		repaint(); // triggers paintComponent
	}
	
	// to let the Dice JPanel know, what size the DiceImage needs
	@Override
	public Dimension getPreferredSize() { //get source for that!!
		return new Dimension(SIZE,SIZE);
	}
	@Override
	public Dimension getMinimumSize() {
	    return new Dimension(SIZE, SIZE);
	}
	@Override
	public Dimension getMaximumSize() {
	    return new Dimension(SIZE, SIZE);
	}
	
	@Override
	public void paintComponent (Graphics g) {
		int width = getWidth();
		int height = getHeight();
		
		super.paintComponent(g); // clear background
		Graphics2D g2 = (Graphics2D) g; // get Graphics2D features
		g2.setColor(Color.WHITE);
		g2.fillRoundRect(0, 0, width, height, 15, 15);
		g2.setColor(Color.LIGHT_GRAY);
		g2.drawRoundRect(0, 0, width - 1, height - 1, 15, 15);
		g2.setColor(Color.BLACK);
		
		List<Integer> putPointAt = new ArrayList<>();
		
		// dice image as a 3X3 grid:            e.g. five:
		// 1 2 3								x(1)   x(3)
		// 4 5 6								    x(5)
		// 7 8 9								x(7)   x(9)
		switch(value) {
			case 1: putPointAt.add(5);
			    break;
			case 2: putPointAt.add(3);
					putPointAt.add(7);
				break;
			case 3: putPointAt.add(3);
					putPointAt.add(5);
					putPointAt.add(7);
				break;
			case 4: putPointAt.add(1);
					putPointAt.add(3);
					putPointAt.add(7);
					putPointAt.add(9);
				break;
			case 5: putPointAt.add(1);
					putPointAt.add(3);
					putPointAt.add(5);
					putPointAt.add(7);
					putPointAt.add(9);
				break;
			case 6: putPointAt.add(1);
					putPointAt.add(3);
					putPointAt.add(4);
					putPointAt.add(6);
					putPointAt.add(7);
					putPointAt.add(9);
				break;
			default:
				break;
		}
		
		for(int i : putPointAt) {
			drawPoint(i,g2, width, height);
		}
		
	}
	
	private void drawPoint(int i, Graphics2D g2, int width, int height) {
		
		int sizePoint = width/5;
		int xCenter = width/2-sizePoint/2;
		int xLeft = width/4-sizePoint/2;
		int xRight = width*3/4-sizePoint/2;
		int yCenter = height/2-sizePoint/2;
		int yUp = height/4-sizePoint/2;
		int yDown = height*3/4-sizePoint/2;
		
		// dice image as a 3X3 grid:
		// 1 2 3
		// 4 5 6
		// 7 8 9
		switch(i) {
		case 1: 
			g2.fillOval(xLeft, yUp, sizePoint, sizePoint);
			break;
		case 3: 
			g2.fillOval(xRight, yUp, sizePoint, sizePoint);
			break;
		case 4: 
			g2.fillOval(xLeft, yCenter, sizePoint, sizePoint);
			break;
		case 5: 
			g2.fillOval(xCenter, yCenter, sizePoint, sizePoint);
			break;
		case 6: 
			g2.fillOval(xRight, yCenter, sizePoint, sizePoint);
			break;
		case 7: 
			g2.fillOval(xLeft, yDown, sizePoint, sizePoint);
			break;
		case 9: 
			g2.fillOval(xRight, yDown, sizePoint, sizePoint);
			break;
		default:
			break;
		}
	}
}
